[package]
name = "tetris-rs-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "*", features = ["wasm_js"] }
rand = "0.9.2"
tetris-rs = { git = "https://github.com/WHMHammer/tetris-rs.git" }
wasm-bindgen = "0.2.105"
