[package]
name = "tetris-rs-wasm"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "*", features = ["wasm_js"] }
js-sys = "0.3.83"
rand = "0.9.2"
tetris-rs = { path = "./submodules/tetris-rs" }
wasm-bindgen = "0.2.105"
